version: '3.3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: webapp:1.0
    container_name: web
    restart: always
    volumes:
      - '.:/usr/src/app'
    env_file:
      - .env.local
    ports:
      - "5000:5000"
    network_mode: host